// Generated by gencpp from file speech/RecognizeUserResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_MESSAGE_RECOGNIZEUSERRESPONSE_H
#define SPEECH_MESSAGE_RECOGNIZEUSERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech
{
template <class ContainerAllocator>
struct RecognizeUserResponse_
{
  typedef RecognizeUserResponse_<ContainerAllocator> Type;

  RecognizeUserResponse_()
    : user()  {
    }
  RecognizeUserResponse_(const ContainerAllocator& _alloc)
    : user(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;





  typedef boost::shared_ptr< ::speech::RecognizeUserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech::RecognizeUserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeUserResponse_

typedef ::speech::RecognizeUserResponse_<std::allocator<void> > RecognizeUserResponse;

typedef boost::shared_ptr< ::speech::RecognizeUserResponse > RecognizeUserResponsePtr;
typedef boost::shared_ptr< ::speech::RecognizeUserResponse const> RecognizeUserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech::RecognizeUserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech::RecognizeUserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech::RecognizeUserResponse_<ContainerAllocator1> & lhs, const ::speech::RecognizeUserResponse_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech::RecognizeUserResponse_<ContainerAllocator1> & lhs, const ::speech::RecognizeUserResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech::RecognizeUserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech::RecognizeUserResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::RecognizeUserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::RecognizeUserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::RecognizeUserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::RecognizeUserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech::RecognizeUserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334ea0b9dd53b20b1554937c6dd08782";
  }

  static const char* value(const ::speech::RecognizeUserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334ea0b9dd53b20bULL;
  static const uint64_t static_value2 = 0x1554937c6dd08782ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech::RecognizeUserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech/RecognizeUserResponse";
  }

  static const char* value(const ::speech::RecognizeUserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech::RecognizeUserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n"
"\n"
;
  }

  static const char* value(const ::speech::RecognizeUserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech::RecognizeUserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeUserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech::RecognizeUserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech::RecognizeUserResponse_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_MESSAGE_RECOGNIZEUSERRESPONSE_H
