// Generated by gencpp from file speech/Speech2TextResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_MESSAGE_SPEECH2TEXTRESPONSE_H
#define SPEECH_MESSAGE_SPEECH2TEXTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech
{
template <class ContainerAllocator>
struct Speech2TextResponse_
{
  typedef Speech2TextResponse_<ContainerAllocator> Type;

  Speech2TextResponse_()
    : text()  {
    }
  Speech2TextResponse_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::speech::Speech2TextResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech::Speech2TextResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Speech2TextResponse_

typedef ::speech::Speech2TextResponse_<std::allocator<void> > Speech2TextResponse;

typedef boost::shared_ptr< ::speech::Speech2TextResponse > Speech2TextResponsePtr;
typedef boost::shared_ptr< ::speech::Speech2TextResponse const> Speech2TextResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech::Speech2TextResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech::Speech2TextResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech::Speech2TextResponse_<ContainerAllocator1> & lhs, const ::speech::Speech2TextResponse_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech::Speech2TextResponse_<ContainerAllocator1> & lhs, const ::speech::Speech2TextResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech::Speech2TextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech::Speech2TextResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::Speech2TextResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::Speech2TextResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::Speech2TextResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::Speech2TextResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech::Speech2TextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::speech::Speech2TextResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech::Speech2TextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech/Speech2TextResponse";
  }

  static const char* value(const ::speech::Speech2TextResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech::Speech2TextResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
"\n"
;
  }

  static const char* value(const ::speech::Speech2TextResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech::Speech2TextResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speech2TextResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech::Speech2TextResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech::Speech2TextResponse_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_MESSAGE_SPEECH2TEXTRESPONSE_H
