// Generated by gencpp from file speech/SpeechRequestResponse.msg
// DO NOT EDIT!


#ifndef SPEECH_MESSAGE_SPEECHREQUESTRESPONSE_H
#define SPEECH_MESSAGE_SPEECHREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace speech
{
template <class ContainerAllocator>
struct SpeechRequestResponse_
{
  typedef SpeechRequestResponse_<ContainerAllocator> Type;

  SpeechRequestResponse_()
    : user()
    , message()  {
    }
  SpeechRequestResponse_(const ContainerAllocator& _alloc)
    : user(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::speech::SpeechRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech::SpeechRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechRequestResponse_

typedef ::speech::SpeechRequestResponse_<std::allocator<void> > SpeechRequestResponse;

typedef boost::shared_ptr< ::speech::SpeechRequestResponse > SpeechRequestResponsePtr;
typedef boost::shared_ptr< ::speech::SpeechRequestResponse const> SpeechRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech::SpeechRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech::SpeechRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech::SpeechRequestResponse_<ContainerAllocator1> & lhs, const ::speech::SpeechRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.user == rhs.user &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech::SpeechRequestResponse_<ContainerAllocator1> & lhs, const ::speech::SpeechRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech::SpeechRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech::SpeechRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::SpeechRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::SpeechRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::SpeechRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::SpeechRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech::SpeechRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bddd90b3dacb0ebe9067797037b379e9";
  }

  static const char* value(const ::speech::SpeechRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbddd90b3dacb0ebeULL;
  static const uint64_t static_value2 = 0x9067797037b379e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech::SpeechRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech/SpeechRequestResponse";
  }

  static const char* value(const ::speech::SpeechRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech::SpeechRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user\n"
"string message\n"
;
  }

  static const char* value(const ::speech::SpeechRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech::SpeechRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech::SpeechRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech::SpeechRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_MESSAGE_SPEECHREQUESTRESPONSE_H
