// Generated by gencpp from file speech/SpeechRequestRequest.msg
// DO NOT EDIT!


#ifndef SPEECH_MESSAGE_SPEECHREQUESTREQUEST_H
#define SPEECH_MESSAGE_SPEECHREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int16MultiArray.h>

namespace speech
{
template <class ContainerAllocator>
struct SpeechRequestRequest_
{
  typedef SpeechRequestRequest_<ContainerAllocator> Type;

  SpeechRequestRequest_()
    : audio()  {
    }
  SpeechRequestRequest_(const ContainerAllocator& _alloc)
    : audio(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int16MultiArray_<ContainerAllocator>  _audio_type;
  _audio_type audio;





  typedef boost::shared_ptr< ::speech::SpeechRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::speech::SpeechRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechRequestRequest_

typedef ::speech::SpeechRequestRequest_<std::allocator<void> > SpeechRequestRequest;

typedef boost::shared_ptr< ::speech::SpeechRequestRequest > SpeechRequestRequestPtr;
typedef boost::shared_ptr< ::speech::SpeechRequestRequest const> SpeechRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::speech::SpeechRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::speech::SpeechRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::speech::SpeechRequestRequest_<ContainerAllocator1> & lhs, const ::speech::SpeechRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.audio == rhs.audio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::speech::SpeechRequestRequest_<ContainerAllocator1> & lhs, const ::speech::SpeechRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace speech

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::speech::SpeechRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::speech::SpeechRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::SpeechRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::speech::SpeechRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::SpeechRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::speech::SpeechRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::speech::SpeechRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9844585fce68eeb17ddcc94f22bd4e26";
  }

  static const char* value(const ::speech::SpeechRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9844585fce68eeb1ULL;
  static const uint64_t static_value2 = 0x7ddcc94f22bd4e26ULL;
};

template<class ContainerAllocator>
struct DataType< ::speech::SpeechRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "speech/SpeechRequestRequest";
  }

  static const char* value(const ::speech::SpeechRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::speech::SpeechRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int16MultiArray audio\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int16MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int16[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::speech::SpeechRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::speech::SpeechRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.audio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::speech::SpeechRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::speech::SpeechRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "audio: ";
    s << std::endl;
    Printer< ::std_msgs::Int16MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.audio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPEECH_MESSAGE_SPEECHREQUESTREQUEST_H
