(cl:defpackage speech-srv
  (:use )
  (:export
   "RECOGNIZEUSER"
   "<RECOGNIZEUSER-REQUEST>"
   "RECOGNIZEUSER-REQUEST"
   "<RECOGNIZEUSER-RESPONSE>"
   "RECOGNIZEUSER-RESPONSE"
   "SPEECH2TEXT"
   "<SPEECH2TEXT-REQUEST>"
   "SPEECH2TEXT-REQUEST"
   "<SPEECH2TEXT-RESPONSE>"
   "SPEECH2TEXT-RESPONSE"
   "SPEECHREQUEST"
   "<SPEECHREQUEST-REQUEST>"
   "SPEECHREQUEST-REQUEST"
   "<SPEECHREQUEST-RESPONSE>"
   "SPEECHREQUEST-RESPONSE"
  ))

