// Generated by gencpp from file chatbot/DialogueRequest.msg
// DO NOT EDIT!


#ifndef CHATBOT_MESSAGE_DIALOGUEREQUEST_H
#define CHATBOT_MESSAGE_DIALOGUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatbot
{
template <class ContainerAllocator>
struct DialogueRequest_
{
  typedef DialogueRequest_<ContainerAllocator> Type;

  DialogueRequest_()
    : message()
    , user()  {
    }
  DialogueRequest_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , user(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _user_type;
  _user_type user;





  typedef boost::shared_ptr< ::chatbot::DialogueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatbot::DialogueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DialogueRequest_

typedef ::chatbot::DialogueRequest_<std::allocator<void> > DialogueRequest;

typedef boost::shared_ptr< ::chatbot::DialogueRequest > DialogueRequestPtr;
typedef boost::shared_ptr< ::chatbot::DialogueRequest const> DialogueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatbot::DialogueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatbot::DialogueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chatbot::DialogueRequest_<ContainerAllocator1> & lhs, const ::chatbot::DialogueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.user == rhs.user;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chatbot::DialogueRequest_<ContainerAllocator1> & lhs, const ::chatbot::DialogueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chatbot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::DialogueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatbot::DialogueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::DialogueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatbot::DialogueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::DialogueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatbot::DialogueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatbot::DialogueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d82fc1fd306cc656c0a43e2ad4e7cbc";
  }

  static const char* value(const ::chatbot::DialogueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d82fc1fd306cc65ULL;
  static const uint64_t static_value2 = 0x6c0a43e2ad4e7cbcULL;
};

template<class ContainerAllocator>
struct DataType< ::chatbot::DialogueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatbot/DialogueRequest";
  }

  static const char* value(const ::chatbot::DialogueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatbot::DialogueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"string user\n"
;
  }

  static const char* value(const ::chatbot::DialogueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatbot::DialogueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.user);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatbot::DialogueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chatbot::DialogueRequest_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "user: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.user);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHATBOT_MESSAGE_DIALOGUEREQUEST_H
