// Generated by gencpp from file pepper_interface/ExecuteJS.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_EXECUTEJS_H
#define PEPPER_INTERFACE_MESSAGE_EXECUTEJS_H

#include <ros/service_traits.h>


#include <pepper_interface/ExecuteJSRequest.h>
#include <pepper_interface/ExecuteJSResponse.h>


namespace pepper_interface
{

struct ExecuteJS
{

typedef ExecuteJSRequest Request;
typedef ExecuteJSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteJS
} // namespace pepper_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_interface::ExecuteJS > {
  static const char* value()
  {
    return "0bc1212ef5c5830fe8dbd8060c89a89d";
  }

  static const char* value(const ::pepper_interface::ExecuteJS&) { return value(); }
};

template<>
struct DataType< ::pepper_interface::ExecuteJS > {
  static const char* value()
  {
    return "pepper_interface/ExecuteJS";
  }

  static const char* value(const ::pepper_interface::ExecuteJS&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_interface::ExecuteJSRequest> should match
// service_traits::MD5Sum< ::pepper_interface::ExecuteJS >
template<>
struct MD5Sum< ::pepper_interface::ExecuteJSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::ExecuteJS >::value();
  }
  static const char* value(const ::pepper_interface::ExecuteJSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::ExecuteJSRequest> should match
// service_traits::DataType< ::pepper_interface::ExecuteJS >
template<>
struct DataType< ::pepper_interface::ExecuteJSRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::ExecuteJS >::value();
  }
  static const char* value(const ::pepper_interface::ExecuteJSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_interface::ExecuteJSResponse> should match
// service_traits::MD5Sum< ::pepper_interface::ExecuteJS >
template<>
struct MD5Sum< ::pepper_interface::ExecuteJSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::ExecuteJS >::value();
  }
  static const char* value(const ::pepper_interface::ExecuteJSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::ExecuteJSResponse> should match
// service_traits::DataType< ::pepper_interface::ExecuteJS >
template<>
struct DataType< ::pepper_interface::ExecuteJSResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::ExecuteJS >::value();
  }
  static const char* value(const ::pepper_interface::ExecuteJSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_EXECUTEJS_H
