// Generated by gencpp from file pepper_interface/LoadURLResponse.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_LOADURLRESPONSE_H
#define PEPPER_INTERFACE_MESSAGE_LOADURLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pepper_interface
{
template <class ContainerAllocator>
struct LoadURLResponse_
{
  typedef LoadURLResponse_<ContainerAllocator> Type;

  LoadURLResponse_()
    : ack()  {
    }
  LoadURLResponse_(const ContainerAllocator& _alloc)
    : ack(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::pepper_interface::LoadURLResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_interface::LoadURLResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadURLResponse_

typedef ::pepper_interface::LoadURLResponse_<std::allocator<void> > LoadURLResponse;

typedef boost::shared_ptr< ::pepper_interface::LoadURLResponse > LoadURLResponsePtr;
typedef boost::shared_ptr< ::pepper_interface::LoadURLResponse const> LoadURLResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_interface::LoadURLResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pepper_interface::LoadURLResponse_<ContainerAllocator1> & lhs, const ::pepper_interface::LoadURLResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pepper_interface::LoadURLResponse_<ContainerAllocator1> & lhs, const ::pepper_interface::LoadURLResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pepper_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::LoadURLResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::LoadURLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::LoadURLResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::pepper_interface::LoadURLResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6a73f722475d64aULL;
  static const uint64_t static_value2 = 0x28238118997ef482ULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_interface/LoadURLResponse";
  }

  static const char* value(const ::pepper_interface::LoadURLResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ack\n"
;
  }

  static const char* value(const ::pepper_interface::LoadURLResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadURLResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_interface::LoadURLResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_interface::LoadURLResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_LOADURLRESPONSE_H
