// Generated by gencpp from file pepper_interface/LoadURLRequest.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_LOADURLREQUEST_H
#define PEPPER_INTERFACE_MESSAGE_LOADURLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pepper_interface
{
template <class ContainerAllocator>
struct LoadURLRequest_
{
  typedef LoadURLRequest_<ContainerAllocator> Type;

  LoadURLRequest_()
    : URL()  {
    }
  LoadURLRequest_(const ContainerAllocator& _alloc)
    : URL(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _URL_type;
  _URL_type URL;





  typedef boost::shared_ptr< ::pepper_interface::LoadURLRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_interface::LoadURLRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadURLRequest_

typedef ::pepper_interface::LoadURLRequest_<std::allocator<void> > LoadURLRequest;

typedef boost::shared_ptr< ::pepper_interface::LoadURLRequest > LoadURLRequestPtr;
typedef boost::shared_ptr< ::pepper_interface::LoadURLRequest const> LoadURLRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_interface::LoadURLRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pepper_interface::LoadURLRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::LoadURLRequest_<ContainerAllocator2> & rhs)
{
  return lhs.URL == rhs.URL;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pepper_interface::LoadURLRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::LoadURLRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pepper_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::LoadURLRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::LoadURLRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::LoadURLRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a6a0ba26cc43dba4acd70369cdccae0";
  }

  static const char* value(const ::pepper_interface::LoadURLRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a6a0ba26cc43dbaULL;
  static const uint64_t static_value2 = 0x4acd70369cdccae0ULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_interface/LoadURLRequest";
  }

  static const char* value(const ::pepper_interface::LoadURLRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string URL\n"
;
  }

  static const char* value(const ::pepper_interface::LoadURLRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.URL);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadURLRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_interface::LoadURLRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_interface::LoadURLRequest_<ContainerAllocator>& v)
  {
    s << indent << "URL: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.URL);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_LOADURLREQUEST_H
