// Generated by gencpp from file pepper_interface/LoadURL.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_LOADURL_H
#define PEPPER_INTERFACE_MESSAGE_LOADURL_H

#include <ros/service_traits.h>


#include <pepper_interface/LoadURLRequest.h>
#include <pepper_interface/LoadURLResponse.h>


namespace pepper_interface
{

struct LoadURL
{

typedef LoadURLRequest Request;
typedef LoadURLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadURL
} // namespace pepper_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_interface::LoadURL > {
  static const char* value()
  {
    return "942def4e0bcb8d3832c8ce342404f80a";
  }

  static const char* value(const ::pepper_interface::LoadURL&) { return value(); }
};

template<>
struct DataType< ::pepper_interface::LoadURL > {
  static const char* value()
  {
    return "pepper_interface/LoadURL";
  }

  static const char* value(const ::pepper_interface::LoadURL&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_interface::LoadURLRequest> should match
// service_traits::MD5Sum< ::pepper_interface::LoadURL >
template<>
struct MD5Sum< ::pepper_interface::LoadURLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::LoadURL >::value();
  }
  static const char* value(const ::pepper_interface::LoadURLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::LoadURLRequest> should match
// service_traits::DataType< ::pepper_interface::LoadURL >
template<>
struct DataType< ::pepper_interface::LoadURLRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::LoadURL >::value();
  }
  static const char* value(const ::pepper_interface::LoadURLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_interface::LoadURLResponse> should match
// service_traits::MD5Sum< ::pepper_interface::LoadURL >
template<>
struct MD5Sum< ::pepper_interface::LoadURLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::LoadURL >::value();
  }
  static const char* value(const ::pepper_interface::LoadURLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::LoadURLResponse> should match
// service_traits::DataType< ::pepper_interface::LoadURL >
template<>
struct DataType< ::pepper_interface::LoadURLResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::LoadURL >::value();
  }
  static const char* value(const ::pepper_interface::LoadURLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_LOADURL_H
