// Generated by gencpp from file pepper_interface/PepperRequestRequest.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_PEPPERREQUESTREQUEST_H
#define PEPPER_INTERFACE_MESSAGE_PEPPERREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pepper_interface
{
template <class ContainerAllocator>
struct PepperRequestRequest_
{
  typedef PepperRequestRequest_<ContainerAllocator> Type;

  PepperRequestRequest_()
    : request()
    , parameter()  {
    }
  PepperRequestRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)
    , parameter(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_type;
  _request_type request;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parameter_type;
  _parameter_type parameter;





  typedef boost::shared_ptr< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PepperRequestRequest_

typedef ::pepper_interface::PepperRequestRequest_<std::allocator<void> > PepperRequestRequest;

typedef boost::shared_ptr< ::pepper_interface::PepperRequestRequest > PepperRequestRequestPtr;
typedef boost::shared_ptr< ::pepper_interface::PepperRequestRequest const> PepperRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_interface::PepperRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pepper_interface::PepperRequestRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::PepperRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request &&
    lhs.parameter == rhs.parameter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pepper_interface::PepperRequestRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::PepperRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pepper_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dff8031db34f64c822e77d998657444b";
  }

  static const char* value(const ::pepper_interface::PepperRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdff8031db34f64c8ULL;
  static const uint64_t static_value2 = 0x22e77d998657444bULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_interface/PepperRequestRequest";
  }

  static const char* value(const ::pepper_interface::PepperRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
"string parameter\n"
;
  }

  static const char* value(const ::pepper_interface::PepperRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
      stream.next(m.parameter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PepperRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_interface::PepperRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_interface::PepperRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request);
    s << indent << "parameter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.parameter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_PEPPERREQUESTREQUEST_H
