// Generated by gencpp from file pepper_interface/PepperRequest.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_PEPPERREQUEST_H
#define PEPPER_INTERFACE_MESSAGE_PEPPERREQUEST_H

#include <ros/service_traits.h>


#include <pepper_interface/PepperRequestRequest.h>
#include <pepper_interface/PepperRequestResponse.h>


namespace pepper_interface
{

struct PepperRequest
{

typedef PepperRequestRequest Request;
typedef PepperRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PepperRequest
} // namespace pepper_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_interface::PepperRequest > {
  static const char* value()
  {
    return "be79cc23dfa148053ca4528d3deb2acf";
  }

  static const char* value(const ::pepper_interface::PepperRequest&) { return value(); }
};

template<>
struct DataType< ::pepper_interface::PepperRequest > {
  static const char* value()
  {
    return "pepper_interface/PepperRequest";
  }

  static const char* value(const ::pepper_interface::PepperRequest&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_interface::PepperRequestRequest> should match
// service_traits::MD5Sum< ::pepper_interface::PepperRequest >
template<>
struct MD5Sum< ::pepper_interface::PepperRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::PepperRequest >::value();
  }
  static const char* value(const ::pepper_interface::PepperRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::PepperRequestRequest> should match
// service_traits::DataType< ::pepper_interface::PepperRequest >
template<>
struct DataType< ::pepper_interface::PepperRequestRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::PepperRequest >::value();
  }
  static const char* value(const ::pepper_interface::PepperRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_interface::PepperRequestResponse> should match
// service_traits::MD5Sum< ::pepper_interface::PepperRequest >
template<>
struct MD5Sum< ::pepper_interface::PepperRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::PepperRequest >::value();
  }
  static const char* value(const ::pepper_interface::PepperRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::PepperRequestResponse> should match
// service_traits::DataType< ::pepper_interface::PepperRequest >
template<>
struct DataType< ::pepper_interface::PepperRequestResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::PepperRequest >::value();
  }
  static const char* value(const ::pepper_interface::PepperRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_PEPPERREQUEST_H
