// Generated by gencpp from file pepper_interface/TalkRequest.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_TALKREQUEST_H
#define PEPPER_INTERFACE_MESSAGE_TALKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pepper_interface
{
template <class ContainerAllocator>
struct TalkRequest_
{
  typedef TalkRequest_<ContainerAllocator> Type;

  TalkRequest_()
    : text()  {
    }
  TalkRequest_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::pepper_interface::TalkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_interface::TalkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TalkRequest_

typedef ::pepper_interface::TalkRequest_<std::allocator<void> > TalkRequest;

typedef boost::shared_ptr< ::pepper_interface::TalkRequest > TalkRequestPtr;
typedef boost::shared_ptr< ::pepper_interface::TalkRequest const> TalkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_interface::TalkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_interface::TalkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pepper_interface::TalkRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::TalkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pepper_interface::TalkRequest_<ContainerAllocator1> & lhs, const ::pepper_interface::TalkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pepper_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::TalkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_interface::TalkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::TalkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_interface::TalkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::TalkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_interface::TalkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_interface::TalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::pepper_interface::TalkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_interface::TalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_interface/TalkRequest";
  }

  static const char* value(const ::pepper_interface::TalkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_interface::TalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::pepper_interface::TalkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_interface::TalkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TalkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_interface::TalkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_interface::TalkRequest_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_TALKREQUEST_H
