// Generated by gencpp from file pepper_interface/WakeUp.msg
// DO NOT EDIT!


#ifndef PEPPER_INTERFACE_MESSAGE_WAKEUP_H
#define PEPPER_INTERFACE_MESSAGE_WAKEUP_H

#include <ros/service_traits.h>


#include <pepper_interface/WakeUpRequest.h>
#include <pepper_interface/WakeUpResponse.h>


namespace pepper_interface
{

struct WakeUp
{

typedef WakeUpRequest Request;
typedef WakeUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WakeUp
} // namespace pepper_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_interface::WakeUp > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::pepper_interface::WakeUp&) { return value(); }
};

template<>
struct DataType< ::pepper_interface::WakeUp > {
  static const char* value()
  {
    return "pepper_interface/WakeUp";
  }

  static const char* value(const ::pepper_interface::WakeUp&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_interface::WakeUpRequest> should match
// service_traits::MD5Sum< ::pepper_interface::WakeUp >
template<>
struct MD5Sum< ::pepper_interface::WakeUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::WakeUp >::value();
  }
  static const char* value(const ::pepper_interface::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::WakeUpRequest> should match
// service_traits::DataType< ::pepper_interface::WakeUp >
template<>
struct DataType< ::pepper_interface::WakeUpRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::WakeUp >::value();
  }
  static const char* value(const ::pepper_interface::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_interface::WakeUpResponse> should match
// service_traits::MD5Sum< ::pepper_interface::WakeUp >
template<>
struct MD5Sum< ::pepper_interface::WakeUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_interface::WakeUp >::value();
  }
  static const char* value(const ::pepper_interface::WakeUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_interface::WakeUpResponse> should match
// service_traits::DataType< ::pepper_interface::WakeUp >
template<>
struct DataType< ::pepper_interface::WakeUpResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_interface::WakeUp >::value();
  }
  static const char* value(const ::pepper_interface::WakeUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_INTERFACE_MESSAGE_WAKEUP_H
