// Generated by gencpp from file audio_recording/VoiceDetectionRequest.msg
// DO NOT EDIT!


#ifndef AUDIO_RECORDING_MESSAGE_VOICEDETECTIONREQUEST_H
#define AUDIO_RECORDING_MESSAGE_VOICEDETECTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace audio_recording
{
template <class ContainerAllocator>
struct VoiceDetectionRequest_
{
  typedef VoiceDetectionRequest_<ContainerAllocator> Type;

  VoiceDetectionRequest_()
    {
    }
  VoiceDetectionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VoiceDetectionRequest_

typedef ::audio_recording::VoiceDetectionRequest_<std::allocator<void> > VoiceDetectionRequest;

typedef boost::shared_ptr< ::audio_recording::VoiceDetectionRequest > VoiceDetectionRequestPtr;
typedef boost::shared_ptr< ::audio_recording::VoiceDetectionRequest const> VoiceDetectionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace audio_recording

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::audio_recording::VoiceDetectionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "audio_recording/VoiceDetectionRequest";
  }

  static const char* value(const ::audio_recording::VoiceDetectionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::audio_recording::VoiceDetectionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VoiceDetectionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audio_recording::VoiceDetectionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::audio_recording::VoiceDetectionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AUDIO_RECORDING_MESSAGE_VOICEDETECTIONREQUEST_H
