// Generated by gencpp from file audio_recording/VoiceDetection.msg
// DO NOT EDIT!


#ifndef AUDIO_RECORDING_MESSAGE_VOICEDETECTION_H
#define AUDIO_RECORDING_MESSAGE_VOICEDETECTION_H

#include <ros/service_traits.h>


#include <audio_recording/VoiceDetectionRequest.h>
#include <audio_recording/VoiceDetectionResponse.h>


namespace audio_recording
{

struct VoiceDetection
{

typedef VoiceDetectionRequest Request;
typedef VoiceDetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VoiceDetection
} // namespace audio_recording


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::audio_recording::VoiceDetection > {
  static const char* value()
  {
    return "9844585fce68eeb17ddcc94f22bd4e26";
  }

  static const char* value(const ::audio_recording::VoiceDetection&) { return value(); }
};

template<>
struct DataType< ::audio_recording::VoiceDetection > {
  static const char* value()
  {
    return "audio_recording/VoiceDetection";
  }

  static const char* value(const ::audio_recording::VoiceDetection&) { return value(); }
};


// service_traits::MD5Sum< ::audio_recording::VoiceDetectionRequest> should match
// service_traits::MD5Sum< ::audio_recording::VoiceDetection >
template<>
struct MD5Sum< ::audio_recording::VoiceDetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::audio_recording::VoiceDetection >::value();
  }
  static const char* value(const ::audio_recording::VoiceDetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::audio_recording::VoiceDetectionRequest> should match
// service_traits::DataType< ::audio_recording::VoiceDetection >
template<>
struct DataType< ::audio_recording::VoiceDetectionRequest>
{
  static const char* value()
  {
    return DataType< ::audio_recording::VoiceDetection >::value();
  }
  static const char* value(const ::audio_recording::VoiceDetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::audio_recording::VoiceDetectionResponse> should match
// service_traits::MD5Sum< ::audio_recording::VoiceDetection >
template<>
struct MD5Sum< ::audio_recording::VoiceDetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::audio_recording::VoiceDetection >::value();
  }
  static const char* value(const ::audio_recording::VoiceDetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::audio_recording::VoiceDetectionResponse> should match
// service_traits::DataType< ::audio_recording::VoiceDetection >
template<>
struct DataType< ::audio_recording::VoiceDetectionResponse>
{
  static const char* value()
  {
    return DataType< ::audio_recording::VoiceDetection >::value();
  }
  static const char* value(const ::audio_recording::VoiceDetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUDIO_RECORDING_MESSAGE_VOICEDETECTION_H
